import { category } from "../../constant";
import {
  JEAN,
  JEAN_NU,
  SHORT_NU,
  SHORT,
  AO_KIEU_NAM,
  AO_KIEU_NU,
  VAY,
  DAM,
  CSDL,
  NMLT,
  KTLT,
} from "../../assets";

export const data = [
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Regular Fit",
    id: "0021624",
    price: 425000,
    category: category.SECOND_HAND,
  },
  {
    title: "Quần jean nữ",
    description: "Kaki",
    src: JEAN_NU,
    name: "Jim Form Slimfit",
    id: "0021625",
    price: 195000,
    category: category.SECOND_HAND,
  },
  {
    title: "Quần short nam",
    description: "Nỉ",
    src: SHORT,
    name: "Regular Fit",
    id: "0021626",
    price: 0,
    category: category.GIVE,
  },
  {
    title: "Quần short nữ",
    description: "Cotton",
    src: SHORT_NU,
    name: "Quần short nữ",
    id: "0021627",
    price: 225000,
    category: category.SECOND_HAND,
  },
  {
    title: "Áo kiểu nam",
    description: "Nỉ",
    src: AO_KIEU_NAM,
    name: "Áo kiểu nam",
    id: "0021629",
    price: 0,
    category: category.GIVE,
  },
  {
    title: "Áo kiểu nữ",
    description: "Cotton",
    src: AO_KIEU_NU,
    name: "Jim Form Slimfit",
    id: "0021630",
    price: 225000,
    category: category.SECOND_HAND,
  },
  {
    title: "Váy",
    description: "Canvas",
    src: VAY,
    name: "Jim Form Slimfit",
    id: "0021631",
    price: 0,
    category: category.GIVE,
  },
  {
    title: "Đầm",
    description: "Cotton",
    src: DAM,
    name: "Loose Fit",
    id: "0021632",
    price: 980000,
    category: category.SECOND_HAND,
  },
  {
    title: "Nhập môn lập trình",
    description: "Sách Nhập môn lập trình",
    src: NMLT,
    name: "Nhập môn lập trình",
    id: "0021633",
    price: 65000,
    category: category.BOOK,
  },
  {
    title: "Cơ Sở Dữ Liệu",
    description: "Sách Cơ Sở Dữ Liệu",
    src: CSDL,
    name: "Cơ Sở Dữ Liệu",
    id: "0021634",
    price: 80000,
    category: category.BOOK,
  },
  {
    title: "Kỹ thuật lập trình",
    description: "Sách Kỹ thuật lập trình",
    src: KTLT,
    name: "Kỹ thuật lập trình",
    id: "0021635",
    price: 100000,
    category: category.BOOK,
  },
];
