import { category } from "../../constant";
import {
  JEAN,
  JEAN_NU,
  SHORT_NU,
  SHORT,
  AO_KIEU_NAM,
  AO_KIEU_NU,
  VAY,
  DAM,
} from "../../assets";

export const data = [
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Regular Fit",
    id: "0021624",
    price: 425000,
    category: category.SECOND_HAND,
  },
  {
    title: "Quần jean nữ",
    description: "Kaki",
    src: JEAN_NU,
    name: "Jim Form Slimfit",
    id: "0021625",
    price: 195000,
    category: category.BOOK,
  },
  {
    title: "Quần short nam",
    description: "Nỉ",
    src: SHORT,
    name: "Regular Fit",
    id: "0021626",
    price: 425000,
    category: category.GIVE,
  },
  {
    title: "Quần short nữ",
    description: "Cotton",
    src: SHORT_NU,
    name: "Oversize",
    id: "0021627",
    price: 225000,
    category: category.SECOND_HAND,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021628",
    price: 125000,
    category: category.SECOND_HAND,
  },
  {
    title: "Áo kiểu nam",
    description: "Nỉ",
    src: AO_KIEU_NAM,
    name: "Oversize",
    id: "0021629",
    price: 420000,
    category: category.GIVE,
  },
  {
    title: "Áo kiểu nữ",
    description: "Cotton",
    src: AO_KIEU_NU,
    name: "Jim Form Slimfit",
    id: "0021630",
    price: 225000,
    category: category.BOOK,
  },
  {
    title: "Váy",
    description: "Canvas",
    src: VAY,
    name: "Jim Form Slimfit",
    id: "0021631",
    price: 1425000,
    category: category.GIVE,
  },
  {
    title: "Đầm",
    description: "Cotton",
    src: DAM,
    name: "Loose Fit",
    id: "0021632",
    price: 980000,
    category: category.SECOND_HAND,
  },
];
