import { JEAN } from "../../assets";
import { category } from "../../constant/category";

export const data = [
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021624",
    price: "425.000",
    category: category.SECOND_HAND,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021625",
    price: "425.000",
    category: category.BOOK,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021626",
    price: "425.000",
    category: category.GIVE,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021627",
    price: "425.000",
    category: category.SECOND_HAND,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021628",
    price: "425.000",
    category: category.SECOND_HAND,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021629",
    price: "425.000",
    category: category.GIVE,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021630",
    price: "425.000",
    category: category.BOOK,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021631",
    price: "425.000",
    category: category.GIVE,
  },
  {
    title: "Quần jean nam",
    description: "Cotton",
    src: JEAN,
    name: "Jim Form Slimfit",
    id: "0021632",
    price: "425.000",
    category: category.SECOND_HAND,
  },
];
